version: '3'

networks:
  backend:
    name: backend

services:
  
  mysql:
    image: 'mysql:latest'
    container_name: godockerDB
    ports:
##      - 3306
      - 9910:3306
##    entrypoint: entrypoint.sh
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    tty: true
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  
  webserver:
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: ./webserver-app
    tty: true
    depends_on: 
      - mysql # This service depends on mysql. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

